input_data_path: "data/raw/heart_cleveland_upload.csv"
target_name: "condition"
splitting_params:
  test_size: 0.25
  random_state: 47
model: sklearn.ensemble.RandomForestClassifier
dump_model: "models/random_forest.pkl"
